apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ppluto-sm-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: ppluto-sm-secrets
    creationPolicy: Owner
  data:
    - secretKey: TEST_SM_SECRET_VERSION
      remoteRef:
        key: prod-TEST_SM_SECRET_VERSION
        version: "1"
