
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ppluto-sm-secrets-c42f6da9c1
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: ppluto-sm-secrets-c42f6da9c1
    creationPolicy: Owner
  data:
    - secretKey: TEST_SM_SECRET_VERSION
      remoteRef:
        key: prod-TEST_SM_SECRET_VERSION
        version: "2"
