{{- $smSecret := print "ppluto-sm-secrets-" (print (data.ToJSON .SECRET_VERSIONS) .SERVER_IMAGE_TAG | crypto.SHA1 | strings.Trunc 10) }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $smSecret }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: {{ $smSecret }}
    creationPolicy: Owner
  data:
{{- range $key, $version := .SECRET_VERSIONS }}
    - secretKey: {{ $key }}
      remoteRef:
        key: prod-{{ $key }}
        version: "{{ $version }}"
{{- end }}
