
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main----hetzner
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: hetzner-temporal
  project: default
  source:
    path: auto_branch_pushes/main/ppluto-main-hetzner/overlays/prod_hetzner
    repoURL: https://github.com/ppluto-dev/argocd-deployments.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

