apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ppluto-server-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: ppluto-server-secret
    creationPolicy: Owner
  data:
{{- range $key, $version := .SERVER_SECRET_VERSIONS }}
    - secretKey: {{ $key }}
      remoteRef:
        key: prod-{{ $key }}
        version: "{{ $version }}"
{{- end }}
